.github/workflows/cla-check.yml, .github/workflows/validate-yaml.yml
add yaml check
Log: add yaml check
=> feat: add yaml check

.github/workflows/auto-sync-workflow.yml
add auto sync
Log: add auto sync
=> feat: add auto sync

.github/workflows/build-tag.yml, workflow-templates/call-build-tag.properties.json, workflow-templates/call-build-tag.yml
add tag_build
Log: add tag_build
=> feat: add tag_build

repos/deepin-community/zssh.json
=> test: test tag-build

.github/workflows/auto-sync-workflow.yml, .github/workflows/templates-sync.yml
when push from action use token
Log: fix trigger sync workflow failed
=> fix: fix push not trigger github action

.github/workflows/auto-sync-workflow.yml
=> fix: fix auto sync

.github/workflows/auto-sync-workflow.yml
=> fix: fix error synatx

.github/workflows/auto-sync-workflow.yml
=> fix: correct

.github/workflows/auto-tag.yml, workflow-templates/call-auto-tag.properties.json, workflow-templates/call-auto-tag.yml
add auto tag
Log: add auto tag
=> feat: add auto tag

.github/workflows/auto-sync-workflow.yml, .github/workflows/templates-sync.yml
=> fix: remove github token

.github/workflows/auto-sync-workflow.yml, .github/workflows/auto-tag.yml
github token can't trigger push event, use ci-bot token
Log:
=> fix: use ci-bot token push tag

.github/workflows/auto-tag.yml
=> fix: add app id and private key

.github/workflows/auto-tag.yml
=> feat: add tagger

.github/workflows/cla-check.yml
添加飞腾作为企业贡献者
相关：https://github.com/linuxdeepin/.github/pull/359
cc @tsic404 @phytiumss
=> chore: add Phytium as Corporate Contributor

.github/workflows/backup-all-repos-to-gitlabwh.bash, .github/workflows/backup-all-repos-to-gitlabwh.yml
=> feat: Schedule a backup of all repos

.github/workflows/backup-all-repos-to-gitlabwh.yml
=> fix: Missing client binary

.github/workflows/cla-check.yml
=> chore: add Zhaoxin as Corporate Contributor

.github/workflows/templates-sync.yml
update tj-actions/changed-files version
=> fix: Argument list too long

repos/deepin-community/zssh.json
=> chore: remove cla check

repos/deepin-community/zssh.json
=> fix: fix error typo

repos/deepin-community/zssh.json
=> fix: fix typora

.github/workflows/auto-tag.yml
when distribution is UNRELEASED do not create tag
Log:
=> fix: UNRELEASED do not create tag

.github/workflows/auto-tag.yml
update get-emial action,and add token
log:
=> fix: update get-email action

.github/workflows/templates-sync.yml
=> chore: update template-sync commiter

scripts/update.py
whne repo config exists do not re write ot
log:
=> fix: when repo config exists do not rewrite it

scripts/update.py
=> fix: change exclude rules

repos/deepin-community/qt6-languageserver.json
add issue template for Qt pacakges repos
log:
=> chore: add issue template for Qt package repos

.github/workflows/chatOps.yml
=> chore: disable merge comment for chatopt

.github/workflows/build-deb.yml
=> feat: remove api check

.github/workflows/check-code-cap.yml
cap检查是安全相关检查,检查不通过需要对应的人进行review
=> chore(CI): add check code workflow for cap

.github/workflows/check-code.yml, workflow-templates/call-check-code.yml
包含cap检查的调用,后续的静态代码检查统一走这个流程入口,这样就不用频繁批量更新其他项目的工作流文件
=> chore(CI): add check code workflow framework

.github/workflows/chatOps.yml
=> fix(chatops): obs check comment error

.github/workflows/templates-sync.yml
try to fix changed-files list too many caused error
=> chore(CI): tj-actions/changed-files update version

.github/workflows/auto-integration-pr.yml, .github/workflows/chatOps.yml
跨组织引用的流程还是存在secrets不能正确获取的问题,因此目前只能通过本组织重新添加来解决这个问题
=> fix(CI): use auto-integration-pr.yml failed

.github/workflows/chatOps.yml, OWNERS
=> Add owner file and update chatopt file

.github/workflows/auto-integration-pr.yml
=> chore(CI): enhance /integrate workflow

.github/workflows/auto-integration-pr.yml, .github/workflows/auto-tag.yml, .github/workflows/chatOps.yml
=> fix(CI): github scripts get token error

.github/workflows/auto-integration-pr.yml
for multi packages integrate with topic
log:
=> chore(CI): Add auto integration workflow to queu

.github/workflows/auto-integration-pr.yml
=> chore(CI): Remove unused 'order' field at integrate workflow

.github/workflows/chatOps.yml
1. 取消最大webhook寻找限制
2. 添加webhook delivery 信息查询并更加pr的number进行过滤,确保找到正确的hook
3. 开始查找并触发webhook时添加评论,这个过程可能比较漫长,因此添加这个提示。
=> feat: 优化‘/check obs'命令

.github/workflows/auto-tag.yml
1. tag创建后项目中开启状态下的pr添加rebase提醒
2. tag创建后添加github release
=> Inhance tag

.github/workflows/auto-integration-pr.yml
=> fix: /integrate command error

.github/workflows/auto-tag.yml, .github/workflows/chatOps.yml
新版本require存在问题,需要等https://github.com/octokit/octokit.js/pull/2665 合并才能正常
=> fix(CI): use old octokit version to support require
